import os
import tempfile
from fpdf import FPDF
from datetime import datetime

def create_pdf(total, positive, negative, chart_path):

    pdf = FPDF()

    pdf.add_page()

    # Title
    pdf.set_fill_color(200, 220, 255)

    pdf.set_font("Arial", "B", 16)

    pdf.cell(
        0,
        12,
        "Business Health Overview",
        ln=True,
        fill=True
        )
    pdf.ln(10)

    # Overview Section
    pdf.set_font("Arial", "B", 14)
    

    pdf.ln(5)

    pdf.set_font("Arial", size=12)

    pdf.cell(200, 10, f"Total Reviews: {total}", ln=True)
    pdf.cell(200, 10, f"Positive Reviews: {positive}", ln=True)
    pdf.cell(200, 10, f"Negative Reviews: {negative}", ln=True)

    pdf.ln(10)
    current_time = datetime.now().strftime("%d-%m-%Y %H:%M")

    pdf.cell(200, 10, f"Generated On: {current_time}", ln=True)    

    # Summary
    if positive > negative:
        summary = "Overall customer sentiment is favorable."
    else:
        summary = "Customer feedback indicates improvement areas in service."
    pdf.multi_cell(0, 10, f"Summary: {summary}")

    

    if os.path.exists(chart_path):
        pdf.ln(5)
        pdf.image(chart_path, x=45, w=100)
    #Insights
    pdf.ln(5)

    pdf.set_font("Arial", "B", 13)
    pdf.cell(200, 10, "Key Insights", ln=True)

    pdf.set_font("Arial", "", 11)

    if positive > negative:
        insight = (
            "Customer sentiment is mostly positive. "
            "Customers appear satisfied with the service experience."
    )
    else:
        insight = (
            "Negative sentiment is higher than positive sentiment. "
            "This suggests improvements are needed in customer experience."
    )

    pdf.multi_cell(0, 8, insight)


#Recommendations
    pdf.ln(5)

    pdf.set_font("Arial", "B", 13)
    pdf.cell(200, 10, "Recommendations", ln=True)

    pdf.set_font("Arial", "", 11)

    if negative > positive:
        recommendation = (
            "Focus on resolving recurring complaints and improving "
            "customer support response time."
    )
    else:
        recommendation = (
            "Maintain current service quality and continue monitoring "
            "customer satisfaction trends."
    )

    pdf.multi_cell(0, 8, recommendation)

    pdf.ln(10)

    pdf.set_font("Arial", "I", 10)

    pdf.cell(
        0,
        10,
        "Generated by BizInsight AI",
        ln=True,
        align="R"
    )

    # Save PDF
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_pdf:
        pdf_path = tmp_pdf.name

    pdf.output(pdf_path)

    return pdf_path

    
    
